# Version of the specs, only for internal usage if this format should ever change
_specver: 1

# modpack related settings, changes the supposed to change the visual appearance of the launcher
modpack:
  # Name of the mod pack, that is displayed in various places where it fits
  name: Starpack Aleph

  # Description
  description: Star's custom modpack.



# settings regarding the installation of the modpack
install:
  # version of minecraft, needs the exact version
  mcVersion: 1.16.5

  # exact version of forge that is supposed to be used
  # if this value is a null value so ( ~, null, or "" ) then the version from the mod pack is going to be used
  forgeVersion: ~

  # If a custom installer is supposed to used, specify the url here: (Otherwise put "", ~ or null here)
  forgeInstallerUrl: ~

  # Link to where the file where the modpack can be distributed
  # This supports loading from local files as well for most pack types if there is file://{PathToFile} in the beginning
  modpackUrl: https://media.forgecdn.net/files/3238/811/Starpack-Aleph-0.1.5.zip

  # This is used to specify in which format the modpack is distributed, the server launcher has to handle each individually if their format differs
  # current supported formats:
  # - curseforge or curse
  # - curseid
  # - zip or zipfile
  modpackFormat: curseforge

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 32274
      -	232791
      - 334853
      - 332522
      - 263420
      - 238372
      - 243478
      - 317780
      - 232131
      - 231275
      - 367706
      - 243863
      - 325492
      - 296468
      - 308240
      - 362791
      - 326950
      - 237701
      - 391382
      - 358191
      - 271740
      - 428199
      - 431430
      - 254284

  # The base path where the server should be installed to, ~ for current path
  baseInstallPath: ~

  # a list of files which are supposed to be ignored when installing it from the client files
  # this can either use regex or glob {default glob: https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-}
  # specify with regex:.... or glob:.... if you want to force a matching type
  ignoreFiles:
    - mods/optifine*.jar
    - resources/**
    - packmenu/**

   # This makes the program check the folder for whether it is supposed to use the
  checkFolder: yes

  # Whether to install Forge or not, should always be yes/true unless you only want to install the pack
  installForge: yes

# settings regarding the launching of the pack
launch:
  # applies the launch wrapper to fix sponge for a few mods
  spongefix: no

  # Use a RAMDisk for the world folder
  # case-sensitive; use only lowercase `yes` or `no`
  # NOTE: The server must have run once fully before switching to `yes`!
  ramDisk: no

  # checks with the help of a few unrelated server whether the server is online
  checkOffline: no

  # specifies the max amount of ram the server is supposed to launch with
  maxRam: 7G

  # specifies whether the server is supposed to auto restart after crash
  autoRestart: yes

  # after a given amount of crashes in a given time the server will stop auto restarting
  crashLimit: 10

  # Time a crash should be still accounted for in the {crashLimit}
  # syntax is either [number]h or [number]min or [number]s
  crashTimer: 60min

  # Arguments that need to go before the 'java' argument, something like linux niceness
  # This is only a string, not a list.
  preJavaArgs: ~

  # Java args that are supposed to be used when the server launches
  # keep in mind java args often need ' - ' in front of it to work, use clarifying parentheses to make sure it uses it correctly
  javaArgs:
    - "-d64"
    - "-server"
    - "-XX:+AggressiveOpts"
    - "-XX:ParallelGCThreads=4"
    - "-XX:+UseConcMarkSweepGC"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+UseParNewGC"
    - "-XX:+ExplicitGCInvokesConcurrent"
    - "-XX:MaxGCPauseMillis=10"
    - "-XX:GCPauseIntervalMillis=50"
    - "-XX:+UseFastAccessorMethods"
    - "-XX:+OptimizeStringConcat"
    - "-XX:NewSize=84m"
    - "-XX:+UseAdaptiveGCBoundary"
    - "-XX:NewRatio=3"
    - "-Dfml.readTimeout=300"
    - "-Dfml.queryResult=confirm"