
[custom_weaponry]

	[custom_weaponry.sample]
		registry_name = "epicfight:registryname"
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, BOW, CROSSBOW
		weapon_type = "SWORD"
		impact = 0.5
		armor_ignorance = 0.0
		hit_at_once = 1

[custom_armor]

	[custom_armor.sample]
		registry_name = "epicfight:registryname"
		stunArmor = 0.0
		weight = 0.0

