
#Simple Sponge Config
[sponge]
	#Set the durability for a Sponge On A Stick
	#Range: > 1
	spongeOnAStickMaxDamage = 256
	#Set the range for a Sponge
	#Range: 1 ~ 64
	spongeRange = 3
	#Set the range for a Sponge On A Stick
	#Range: 1 ~ 64
	spongeOnAStickRange = 3

[magmatic_sponge]
	#Set the durability for a Magmatic Sponge On A Stick
	#Range: > 1
	magmaticSpongeOnAStickMaxDamage = 256
	#Set the range for a Magmatic Sponge
	#Range: 1 ~ 64
	magmaticSpongeRange = 3
	#Set the range for a Magmatic Sponge On A Stick
	#Range: 1 ~ 64
	magmaticSpongeOnAStickRange = 3

[energized_sponge]
	#Set to true to enable the Energized Sponge On A Stick
	enableEnergizedSpongeOnAStick = true
	#Set the max energy for an Energized Sponge On A Stick
	#Range: > 1
	energizedSpongeOnAStickMaxEnergy = 500000
	#Set the per right click energy use for an Energized Sponge On A Stick
	#Range: 1 ~ 10000
	energizedSpongeOnAStickPerRightClickUse = 100
	#Set the range for an Energized Sponge On A Stick
	#Range: 1 ~ 64
	energizedSpongeOnAStickRange = 7

[compressed_sponge]
	#Set the durability (multiplied by 9) for a Compressed Sponge On A Stick
	#Range: > 1
	compressedSpongeOnAStickMaxDamage = 256
	#Set the range (multiplied by 2) for a Compressed Sponge On A Stick
	#Range: 1 ~ 64
	compressedSpongeOnAStickRange = 3
	#Set the durability (multiplied by 9) for a Compressed Magmatic Sponge On A Stick
	#Range: > 1
	compressedMagmaticSpongeOnAStickMaxDamage = 256
	#Set the range (multiplied by 2) for a Compressed Magmatic Sponge On A Stick
	#Range: 1 ~ 64
	compressedMagmaticSpongeOnAStickRange = 3

[misc]
	#When OpenBlocks is detected, certain crafting recipes will be changed / disabled.
	#Set this to false if you wish to use the sponges from this mod.
	#You'll have to use CraftTweaker to prevent recipe conflicts.
	openBlocksIntegration = true

