
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 8006736

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

[crossroads]
	#The byproduct material to output in Crossroads' Millstone.
	byproduct = "minecraft:sand"

[futurepack]
	#The byproduct material to output in Futurepack's Centrifuge.
	byproduct = "minecraft:cobblestone"

