
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 8411814

[create]
	#The byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[crossroads]
	#The byproduct material to output in Crossroads' Millstone.
	byproduct = "minecraft:sand"

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

